activation: silu
aggr: add
atom_types:
- 1
- 5
- 6
- 7
- 8
- 9
- 11
- 14
- 15
- 16
- 17
- 20
- 22
- 23
- 24
- 26
- 27
- 28
- 30
- 32
- 33
- 34
- 35
- 40
- 42
- 46
- 48
- 49
- 50
- 51
- 53
- 66
- 70
- 78
- 79
- 80
- 81
- 83
attn_activation: silu
batch_size: 16
charge: false
compute_d4_atomic: false
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 12.0
dataset: MoleculeNet
dataset_arg:
  conformer: best
  data_version: geom
  dataset: tox21
  num_conformers: 1
dataset_root: ./data/MoleculeNet
dataset_split: null
derivative: false
distance_influence: both
early_stopping_patience: 25
ema_alpha_dy: 1.0
ema_alpha_y: 1.0
embed_files: null
embedding_dimension: 128
energy_files: null
energy_tox_multi_task: false
energy_weight: 0.0
force_files: null
force_weight: 0.0
inference_batch_size: 16
layernorm_on_vec: whitened
linear_probing: false
load_model: null
log_dir: output_dir_edge/
long_range_cutoff: 50
lr: 0.0005
lr_cosine_length: 0
lr_factor: 0.75
lr_metric: val_loss
lr_min: 1.0e-08
lr_patience: 5
lr_schedule: reduce_on_plateau
lr_warmup_steps: 0
max_len_smiles: 325
max_num_neighbors: 250
max_z: 100
model: equivariant-transformer-edge
neighbor_embedding: true
ngpus: 1
num_atom_types: 38
num_epochs: 3000
num_heads: 8
num_layers: 5
num_nodes: 1
num_rbf: 64
num_workers: 12
output_channels_toxicity: 12
output_model: Toxicity
output_model_charges: null
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
reset_trainer: false
save_interval: 1
save_top_k: 1
seed: 1
single_task_id: null
spin: false
splits: null
standardize: false
test_checkpoint: ./models/tox21.ckpt
test_interval: 10
test_run: false
test_size: 0.1
toxicity_weight: 1.0
train_size: 0.8
train_type: classification
trainable_rbf: true
use_atom_props: false
use_d4_dispersion: false
use_electrostatics: false
use_energy_feature: false
use_smiles: false
use_smiles_only: false
use_total_charge: false
use_zbl_repulsion: false
val_size: 0.1
wandb: false
weight_decay: 1.0e-05
